#!/usr/local/bin/node

let fs = require("fs");
let Phrase = require("mhartl-palindrome");
let text = fs.readFileSync("phrases.txt", "utf-8");
let palindromesArray = [];

text.split("\n").forEach(function(line) {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    console.log("palindrome detected:", line);
    palindromesArray.push(line);
  }
});

fs.writeFileSync("palindromes.txt", palindromesArray.join("\n"), "utf8");
fs.appendFileSync("palindromes.txt", "\n", "utf8");
